### ISSUE TITLE
[Img thumbnail] Ajout d'un lien vers l'image

### ISSUE THREAD

**Issue by Deevad** [Pluxopolis/plxEditor#4]
Bonsoir,

En cas d'action du lien 'Thumbnail' pour insérer une miniature d'image après avoir utilisé plxEditor, le code retourné dans la fenêtre de composition ressemble à ceci:
```
<img src="data/images/blog/2010/08/13/Mosquitoes-hunter_by_David-Revoy.tb.jpg" />
```

Serait t'il possible d'avoir un lien vers l'image plus grande automatiquement? Par exemple: 
```
<a href="data/images/blog/2010/08/13/Mosquitoes-hunter_by_David-Revoy.jpg" title="click to enlarge">
   <img src="data/images/blog/2010/08/13/Mosquitoes-hunter_by_David-Revoy.tb.jpg" />
</a>
```
Merci,

(Note: super les dernières modifications)

**Comment by Pluxopolis** [comment]
implémenté: https://github.com/Pluxopolis/plxEditor/commit/17d68d5e519360f9058a63da5dda478c0ecaa15b

**Comment by Deevad** [comment]
Fantastique! merci beaucoup @Pluxopolis . 👍
